### ISSUE TITLE
Как можно сделать сет стейт?

### ISSUE THREAD

**Issue by Yuricoden** [mmarkelov/react-nouislider#1]
Мне нужно сделать сет стейт  value в другой функции как ето можно сделать какой метод есть в данном слайдере?

**Comment by mmarkelov** [comment]
@Yuricoden Не совсем понятен вопрос. Что требуется сделать?

**Comment by Yuricoden** [comment]
По сути мне нужно навесить на слайдер какую нибудь функцию которую я могу вызвать где угодно для того чтобы изменить значения для сладера. Например получения новых значений от апи. Вопрос в том каким методом для етого можно воспользоваться?

**Comment by mmarkelov** [comment]
@Yuricoden напрямую через стейт поменять значение фильтра нельзя. Возможно в одном из следующих релизов такой функционал будет добавлен. Можно использовать рефы для этой цели. Вот [пример](https://codesandbox.io/s/o7qvvq7k4z). Ваши пожелания по добавлению этого функционала учтены.

**Comment by mmarkelov** [comment]
Добавил в версию 1.5.0 свойство setStart, которое можно использовать для установки нового значения в слайдер
