### ISSUE TITLE
Specify React as a Peer Dependency

### ISSUE THREAD

**Issue by MrAvantiC** [mmarkelov/react-nouislider#12]
Hi! :)

When using this package in an existing react-project it resulted in the following error:
```
Hooks can only be called inside the body of a function component.
```

After a bit of research I found the following quote in the react documentation:

> If you see more than one React, you’ll need to figure out why this happens and fix your dependency tree. For example, maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency). Until that library is fixed, Yarn resolutions is one possible workaround.

I was able to fix the issue by manually removing the react-directory:
`rm -rf <my-project>/node_modules/nouislider-react/node_modules/react`

Unfortunately that isn't really robust for me since I'd also have to manually edit the `package-lock.json` to ensure the library wouldn't get installed during my CI. Also others might experience the same issue sooner or later.

Do you think it's possible to declare react as a *peer-dependency only* as suggested by the documentation?

**Comment by mmarkelov** [comment]
@MrAvantiC Thank you! Youp, this is totally my mistake. I'll take care of it ASAP

**Comment by mmarkelov** [comment]
@MrAvantiC I just publish new version **3.1.0**. Could you please check it out?

**Comment by MrAvantiC** [comment]
Just updated and it works as expected now.
Thanks for the quick fix!
