### ISSUE TITLE
Ref is not forwarded to noUiSlider

### ISSUE THREAD

**Issue by steliyan** [mmarkelov/react-nouislider#13]
I am planning to use the component, but I want to have access to the `ref` of the **noUiSlider** component.
I need to manually change the set value, something similar to: https://refreshless.com/nouislider/examples/#section-soft-limits

I can't use the **padding**, because the slider I am creating is not linear.

Is there a specific reason why the `ref` is not forwarded or just it was not requested until now?

**Comment by mmarkelov** [comment]
@steliyan it was not requested. But i suppose it is nice to have **ref**. So i'll take care of it

**Comment by steliyan** [comment]
You can check #14 :))

**Comment by mmarkelov** [comment]
@steliyan thank you! I just add ref in **3.2.0**, you can check it out

**Comment by steliyan** [comment]
Great!

I want to add 2 things: 
1. The way the `ref` is set currently, doesn't work if you use [React.createRef](https://github.com/facebook/react/blob/master/packages/react/src/ReactCreateRef.js). That was the point of the [else statement](https://github.com/steliyan/react-nouislider/blob/add-forwardref/src/index.js#L27).
[Here](https://github.com/steliyan/react-nouislider/commit/13be5e5fc0a66c6a039ab5f8aa8568fb8da17d7c) is the desired behaviour, it works as far as I know, I made a simple [example](https://github.com/steliyan/react-nouislider/commit/41992eadb2da6e54bf69be333364cd405188aed5) for it as well.
The clean-up was added based on [this info](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element) from the **React** team.
2. Regarding [your question](https://github.com/mmarkelov/react-nouislider/pull/14#discussion_r292329027), I have the answer now. :))
The reason for it is the ref can be set prior to going to `compononentDidMount`. Note that with `useEffect` is used, then the component has to be rendered first and then you can access the `ref`. This may be undesired in some cases, not sure. I was relying on this behaviour which is not correct, so I think `useEffect` is the proper way to go. :))

Thank you for your quick responses!

**Comment by mmarkelov** [comment]
@steliyan thanks a lot! I add **React.createRef** support in **3.2.1**

**Comment by steliyan** [comment]
Great job, @mmarkelov! :)

My code is working with `createRef`/`useRef` now.

Keep up the good work!

**Comment by Ghadir31** [comment]
Hello. I have the exact same problem (I want to use soft limits in a non-linear slider because padding doesn't work). I followed the documentation, I copy-pasted the exact same code from this section: 
https://www.npmjs.com/package/nouislider-react#using-with-ref
so that I will be able to set up 'ref' - but it wouldn't work. It keeps giving me a 'ref' undefined error. I am not as resourceful as the original poster here, so I don't know how to go about solving this problem. I am on version 3.3.9 of nouislider-react if it matters.
