### ISSUE TITLE
DEV: prettier is not listed in devDependencies

### ISSUE THREAD

**Issue by steliyan** [mmarkelov/react-nouislider#15]
A small thing I noticed is that the `prettier` package is not listed in the project's `devDependencies`, I guess you have it installed globally.

This caused me issues because the pre-commit hooks always failed.

Greetings, Steliyan.

**Comment by mmarkelov** [comment]
@steliyan thanks, that is my fault

**Comment by mmarkelov** [comment]
Fixed
