### ISSUE TITLE
type file

### ISSUE THREAD

**Issue by straxico** [mmarkelov/react-nouislider#16]
hi 
i install 3.3.1 from npm but index.d.ts not updated to latest file
i see this in installed type file

    onChange?(): void;
    onEnd?(): void;
    onSet?(): void;
    onSlide?(): void;
    onStart?(): void;
    onUpdate?(): void;

**Comment by straxico** [comment]
![Capture](https://user-images.githubusercontent.com/6344893/64064152-41174600-cc13-11e9-9822-3f0169412fc1.PNG)

**Comment by mmarkelov** [comment]
@straxico thanks! I just publish new **nouislider-react** version **3.3.2** - this is should fix it
