### ISSUE TITLE
Adding format  to slider change the values of the slider.

### ISSUE THREAD

**Issue by Sibgha228** [mmarkelov/react-nouislider#20]
Hi, 

If I add a format for tooltip it effect the actual values of slider. This issue is not in earlier version but they have same other issues. 

Here is a code pen explaining the issue : 
https://codesandbox.io/s/nouislider-react-example-8rbp8?fontsize=14

Do you know how to fix ?

**Comment by mmarkelov** [comment]
@Sibgha228 can't understand what are talking about. 
Could you provide some info about working version?

**Comment by Sibgha228** [comment]
Hi @mmarkelov 

Here with version 2.3.0 the format of tooltip works as expected:
https://codesandbox.io/s/nouislider-react-example-q3kvf

And with the same code and version 3.3.3, format is not working:
https://codesandbox.io/s/nouislider-react-example-8rbp8

**Comment by mmarkelov** [comment]
@Sibgha228 thank you for extra info! Seems like a bug, I'll take a look soon.

**Comment by mmarkelov** [comment]
@Sibgha228 should be fixed in **3.3.4**

**Comment by Sibgha228** [comment]
@mmarkelov Thanks for the fix. Unfortunately doesn't work with my case :( 

Tried in version 3.3.4 here:
https://codesandbox.io/s/nouislider-react-example-56c12

**Comment by MrAvantiC** [comment]
Hi @mmarkelov ,
I'm not opening a separate issue for my problem because I'm pretty sure it's related to this.

We updated our dependency from 3.3.3 to 3.3.4 and are since then experience infinite loops/updates for the Slider. This causes our site to run at 100% CPU-Load and eventually crash the browser.

With version 3.3.3 (and before) it works just fine.

**Comment by mmarkelov** [comment]
@MrAvantiC Thanks! I deprecate version **3.3.4**

**Comment by mmarkelov** [comment]
@Sibgha228 @MrAvantiC  Can you please check new version **3.3.5**?

**Comment by Sibgha228** [comment]
Works perfectly fine. Thank you.
