### ISSUE TITLE
Update of step is not being forwarded to noUIslider

### ISSUE THREAD

**Issue by Jimmy89** [mmarkelov/react-nouislider#25]
There are two things that I want to address on react-nouislider.

One: The react.memo in the index.js calls:

```js
const areEqual = (prevProps, nextProps) => {
  const { start, disabled, range } = prevProps;
  return (
    isEqual(nextProps.start, start) &&
    nextProps.disabled === disabled &&
    isEqual(nextProps.range, range)
  );
};
```

Which does not cover changes in `step`. While this is something that can be updated and should trigger a re-render.

Two: When you change both the range and the step in order to trigger a re-render the step value is not being adjusted to the new value. Instead, the initialized step value used to initiate the noUISlider keeps being used (no matter how many updates you send). For example: you initialize the step value with 1, then you change that value to 2.

Example code:

```js
const Slider = (props) => {
  const {
    minimum, step, maximum
  } = props;
  const start = 1;
  return <Nouislider range={{ min: minimum, max: maximum }} step={step} start={start} />;
};
```

Now try to render Slider with a dynamic step variable. You will notice that the initialize step value (e.g. 1) is always used as step parameter, even when `step = 2`

**Comment by mmarkelov** [comment]
@Jimmy89 should be fixed in **3.3.6**

**Comment by maps82** [comment]
This definitely doesn't work. Yes, the useEffect is called, and it calls `updateOptions({range, step})` with the updated step. Maybe this is a bug in nouislider? Is there an easy workaround to reinitialize nouislider manually when the step prop changes?

Can we reopen this issue? Thanks!

**Comment by maps82** [comment]
As a workaround, I now force a re-initialization of the Nouislider component by setting it's key to step:

```js
        <Nouislider
          key={step}
          range={{min, max}}
          step={currentStep}
          start={[minValue, maxValue]}
          disabled={disabled}
          onUpdate={handleSliderUpdate}
          onStart={handleSliderStart}
          onEnd={handleSliderEnd}
          connect
          animate={false}
        />
```

This works fine for me, but it's a workaround.

**Comment by mmarkelov** [comment]
@maps82 could you provide some repro?
Just tried to change **step** and it’s seems to be OK
https://codesandbox.io/s/sad-newton-vv5bo?file=/src/App.js

**Comment by maps82** [comment]
I had a useCallback in my code that wasn't updated correctly. 🙈
I'm so sorry, everything works fine. Thanks for your effort and for checking this.

**Comment by mmarkelov** [comment]
@maps82 that’s totally fine. =)
