### ISSUE TITLE
Is there any way to disable certain values of the slider along with its pips on certain conditions ?

### ISSUE THREAD

**Issue by sharathbangera6** [mmarkelov/react-nouislider#29]
Is there any way to disable certain values of the slider along with its pips on certain conditions?

**Comment by mmarkelov** [comment]
@sharathbangera6 I'm not sure what do you exactly want. Could please provide maybe some representation of expected  behavior

**Comment by sharathbangera6** [comment]
@mmarkelov Basically i have set of values as pips to my slider and based one condition I need to disabled few pips or points in my slider.  Incase user slides to these points i just update the slider value to something which is not disabled, but pips should look disabled for me. I used to use jquery slider where I could just disable them by doing dom manipulation. Wanted to know if something is possible with react-noUiSlider.

<img width="686" alt="Screenshot 2020-06-26 at 1 08 07 PM" src="https://user-images.githubusercontent.com/8947305/85832841-6e3e7180-b7ae-11ea-9350-3bc0d4d948ce.png">

**Comment by sharathbangera6** [comment]
Handled it with CSS.
