### ISSUE TITLE
Event handlers not getting rebound

### ISSUE THREAD

**Issue by tiansivive** [mmarkelov/react-nouislider#31]
All the handlers only get bound on creating the slider. This leads to problems with stale state and props if, for example, we want to do different actions depending on state/props.

Here's an [example](https://codesandbox.io/s/react-playground-forked-6b17m?fontsize=14&hidenavigation=1&theme=dark)

Notice how we can never change the `bar` value as `type` is stale, it's always `foo` as that was the captured closure on the initial binding

**Comment by mmarkelov** [comment]
@tiansivive I think that it something that not related to **react-nouislider**.
You can easily fix it with **ref**, I updated your [example](https://codesandbox.io/s/react-playground-forked-8o6u8?file=/index.js)

**Comment by tiansivive** [comment]
It is a `react-nouislider` problem because it doesn't behave as expected in react. 
I've updated my original example with a [counter](https://codesandbox.io/s/react-playground-forked-6fuqw?fontsize=14&hidenavigation=1&theme=dark) for comparison.

Notice the logic is exactly the same, the `update` function depends on the state. In the counter component the new event handler replaces the old one and everything works correctly. In the slider example however, it doesn't.

Using `useRef` is a workaround, not a fix for the problem.
I had to go through the slider source code to understand what was wrong with my application, it's a sign the implementation is leaking. As a user you wouldn't know you need `useRef`, you'd just expect the handlers to be bound properly. Not to mention that `useRef` is discouraged because it introduces mutability and imperative constructs to what is otherwise a functional paradigm. Finally, you're now introducing what essentially amounts to a duplicated variable - which you now have to keep in sync with `useEffect` - in order to overcome the faulty implementation.

I'm a bit stressed for time lately, but I'd be happy to open a PR for a fix if you'll accept it? just not sure when I'd do that

**Comment by mmarkelov** [comment]
@tiansivive sure! You can open a PR

**Comment by Teckden** [comment]
@mmarkelov thank you for the great library but I am having the same problem with handlers. Basically if i use my state in the onChange function it is not refreshed, cause this onChange function is bound only on creating a slider.

Your link with the `ref` solution from this [comment](https://github.com/mmarkelov/react-nouislider/issues/31#issuecomment-707634125) is not working anymore :( Can you please re-share the solution with ref one more time for this [example](https://codesandbox.io/s/react-playground-forked-6b17m?fontsize=14&hidenavigation=1&theme=dark)?

**Comment by mmarkelov** [comment]
@Teckden ok, i'll take a look to fix it in **react-nouislider**
