### ISSUE TITLE
Format does not accept formatter which returns a Number for method 'to'

### ISSUE THREAD

**Issue by JenWa** [mmarkelov/react-nouislider#32]
**Current behaviour**
Currently only formatters are valid which return a `string` for the method `to`. 

**Expected behaviour**
With regard to the documentation of the noUiSlider, it should be possible to have formatters which return `number`  for the method `to`, see [https://refreshless.com/nouislider/number-formatting/](https://refreshless.com/nouislider/number-formatting/).

**Comment by mmarkelov** [comment]
close as #33 was merged
