### ISSUE TITLE
Не отображается компонент

### ISSUE THREAD

**Issue by Azariil** [mmarkelov/react-nouislider#4]
Столкнулся с такоей проблемой. Установил компонент. Решил проверить его работу. Воспользовался первым примером. Слайдер присутствует в DOM но вот высота у всех компонентов равна 0. В чем может быть проичина?
Еще заметил, что IDE выдает следующее предупреждение:

> [ts]
> Could not find a declaration file for module 'nouislider-react'. '/home/azariil/project/node_modules/nouislider-react/build/index.js' implicitly has an 'any' type.
>   Try `npm install @types/nouislider-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'nouislider-react';`

**Comment by Azariil** [comment]
Нашел причину. В примере стили подключаются следующим образом:
`import "nouislider/distribute/nouislider.css";`
Но при таком подключении стили не подгружаются. Попробовал подключить стили в index.html и слайдер отобразился. Но вот как корректно подключить стили пока не придумал. :(
Попробовал просто указать путь имеено к файлу в папке node_modules:
`import "../node_modules/nouislider/distribute/nouislider.css";`
Увы не помогло.

**Comment by mmarkelov** [comment]
@Azariil привет! Прости за долгий ответ. Возможно не используешь css-loader - поэтому стили не подключаются. Было бы неплохо увидеть твой код, чтобы наверняка понять в чем проблема. Со своей стороны постараюсь найти решение для использования стилей слайдера "из коробки"

**Comment by Azariil** [comment]
Спасибо за ответ. Так же извиняюсь за столь долгий ответ. Но причина была в том, что в проекте используется css-loader с генерацией hash для имени классов. Я увы не доглядел сразу. Спасибо еще раз!
