### ISSUE TITLE
Typo in documentation dist instead of distribute

### ISSUE THREAD

**Issue by ghost** [mmarkelov/react-nouislider#48]
When I'm trying to run the following code in my repo 
![image](https://user-images.githubusercontent.com/86713661/157406578-f3a15e7d-1515-4cf4-a2f0-18321502d3bb.png)
I have the following issue
![image](https://user-images.githubusercontent.com/86713661/157406726-9ba1f2d4-6cf8-4cc4-bc8e-9098da66a791.png)
I have checked
It should be **/dist** path instead of **/distribute**
![image](https://user-images.githubusercontent.com/86713661/157406965-04173718-a6b0-4ecc-8e78-d77d3b8382a5.png)

**Comment by tony** [comment]
Fix in #53
