### ISSUE TITLE
Example does not work. Cannot find module 'nouislider'

### ISSUE THREAD

**Issue by doemski** [mmarkelov/react-nouislider#5]
Followed instructions in README:

```
git clone https://github.com/mmarkelov/react-nouislider.git
cd example
npm install && npm run dev
```

Background was rendered, sliders not. Got following errors:

![image](https://user-images.githubusercontent.com/11717392/47717106-14864c80-dc45-11e8-9798-6b17675e9fe1.png)

**Comment by mmarkelov** [comment]
@doemski Thanks for opening issue. You can try to run `npm install` in root directory and then 
`cd example` and `npm install && npm run dev`
But I need to think about how to do it cleaner. Maybe I should change example or readme

**Comment by doemski** [comment]
Hi @mmarkelov , yes this fixed the issue thanks!  :+1:

**Comment by mmarkelov** [comment]
Edit readme for cleaner setup example process https://github.com/mmarkelov/react-nouislider/commit/77661e0b240b5c67c52fc70491eb0ed488da73d5
