### ISSUE TITLE
When passed in updated style props, the slider component does not update.

### ISSUE THREAD

**Issue by TheCrabity** [mmarkelov/react-nouislider#7]
When passed in updated style props (background), the slider component does not update until the slider is moved.

**Comment by mmarkelov** [comment]
@Hermities could you provide some extra info? Code and expected behaviour will be very useful. Thanks!

**Comment by mmarkelov** [comment]
@Hermities I suppose I could understand what do you want. You can check [example](https://codesandbox.io/s/o7qvvq7k4z) - I can implement this soon, but actually I don't see practical usage for this
